<?php

namespace Database\Seeders;

use App\Models\Mission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class MissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $missionData = [
            [
                'title' => 'Operación Tormenta',
                'subtitle' => 'Infiltración en territorio enemigo',
                'description' => 'Misión encubierta para obtener información crucial sobre las actividades enemigas.',
                'date' => '2024-04-10',
                'status' => 'En progreso',
                'type' => 'Reconocimiento',
                'priority' => 'Alta',
                'objective' => 'Recopilar datos sobre posiciones enemigas',
                'action' => 'Infiltración sigilosa en territorio enemigo',
                'result' => 'En progreso',
                // 'photo' => 'https://www.eltiempo.com/files/image_640_428/uploads/2022/07/15/62f7c4b7e8f6f.jpeg',
                'photo' => 'barco.jpg',
                'army_id' => 3,
                'destination_id' => 3,
                'user_id' => 1,
            ],
            [
                'title' => 'Operación Vigilancia Costera',
                'subtitle' => 'Patrulla marítima',
                'description' => 'Misión de vigilancia para asegurar las aguas territoriales y detectar actividades sospechosas.',
                'date' => '2024-04-15',
                'status' => 'En Espera de ejecución',
                'type' => 'Patrulla',
                'priority' => 'Media',
                'objective' => 'Detectar y reportar cualquier actividad no autorizada en el mar',
                'action' => 'Realizar patrullas regulares a lo largo de la costa designada',
                'result' => 'En espera de ejecución',
                // 'photo' => 'https://www.eltiempo.com/files/image_640_428/uploads/2022/07/15/62f7c4b7e8f6f.jpeg',
                'photo' => 'barco.jpg',
                'army_id' => 2,
                'destination_id' => 2,
                'user_id' => 2,
            ],
            [
                'title' => 'Operación Vigilancia Nocturna',
                'subtitle' => 'Patrullaje en áreas sensibles',
                'description' => 'Misión de vigilancia nocturna para monitorear actividades sospechosas en la frontera.',
                'date' => '2024-05-05',
                'status' => 'En progreso',
                'type' => 'Patrulla',
                'priority' => 'Media',
                'objective' => 'Detectar movimientos ilegales en la frontera',
                'action' => 'Patrullaje sigiloso en áreas designadas',
                'result' => 'En progreso',
                // 'photo' => 'https://www.eltiempo.com/files/image_640_428/uploads/2022/07/15/62f7c4b7e8f6f.jpeg',
                'photo' => 'barco.jpg',
                'army_id' => 3,
                'destination_id' => 4,
                'user_id' => 2,
            ],
            [
                'title' => 'Misión Marítima en el Cantábrico',
                'subtitle' => 'Vigilancia y Seguridad Marítima',
                'description' => 'El patrullero de altura "Atalaya" llevó a cabo dos misiones de Vigilancia y Seguridad Marítima desde el sábado 13 de abril, protegiendo los espacios marítimos de soberanía e interés nacional.',
                'date' => '2024-05-06',
                'status' => 'Concluida',
                'type' => 'Seguridad Marítima',
                'priority' => 'Alta',
                'objective' => 'Proteger los espacios marítimos nacionales',
                'action' => 'Vigilancia del tráfico marítimo, supervisión pesquera, protección de rutas marítimas',
                'result' => 'Concluida',
                // 'photo' => 'https://www.eltiempo.com/files/image_640_428/uploads/2022/07/15/62f7c4b7e8f6f.jpeg',
                'photo' => 'barco.jpg',
                'army_id' => 4,
                'destination_id' => 4,
                'user_id' => 3,
            ],
            [
                'title' => 'Ejercicio Multinacional en el Mediterráneo: ESP MINEX-24',
                'subtitle' => 'Guerra de Minas',
                'description' => 'La Armada Española lidera el ejercicio multinacional avanzado "ESP MINEX-24" en aguas del archipiélago balear, con la participación de 13 buques de superficie, un helicóptero SH60B de la Armada y equipos especializados de Bélgica, Estados Unidos y España.',
                'date' => '2024-05-02',
                'status' => 'En progreso',
                'type' => 'Guerra de Minas',
                'priority' => 'Alta',
                'objective' => 'Fortalecer cooperación y interoperabilidad en detección y neutralización de minas marinas',
                'action' => 'Realización de ejercicios de detección y neutralización de minas marinas',
                'result' => 'En progreso',
                // 'photo' => 'https://www.eltiempo.com/files/image_640_428/uploads/2022/07/15/62f7c4b7e8f6f.jpeg',
                'photo' => 'barco.jpg',
                'army_id' => 3,
                'destination_id' => 5,
                'user_id' => 2,
            ],
            // Misiones de 2024
            [
                'title' => 'Operación Montaña Verde',
                'subtitle' => 'Patrulla en terreno montañoso',
                'description' => 'Misión de patrulla en zonas montañosas para detectar posibles rutas de contrabando.',
                'date' => '2024-06-01',
                'status' => 'En progreso',
                'type' => 'Patrulla',
                'priority' => 'Media',
                'objective' => 'Identificar y reportar actividades ilícitas en terreno montañoso',
                'action' => 'Patrullaje en áreas montañosas utilizando equipo especializado',
                'result' => 'En progreso',
                'photo' => 'barco.jpg',
                'army_id' => 2,
                'destination_id' => 7,
                'user_id' => 1,
            ],
            [
                'title' => 'Operación Frontera Segura',
                'subtitle' => 'Control fronterizo',
                'description' => 'Misión de control y vigilancia en la frontera para prevenir el paso de personas y mercancías ilegales.',
                'date' => '2024-06-05',
                'status' => 'En progreso',
                'type' => 'Vigilancia',
                'priority' => 'Alta',
                'objective' => 'Garantizar la seguridad en la frontera y evitar actividades ilegales',
                'action' => 'Instalación de puntos de control y patrullaje constante',
                'result' => 'En progreso',
                'photo' => 'barco.jpg',
                'army_id' => 2,
                'destination_id' => 8,
                'user_id' => 2,
            ],
            [
                'title' => 'Operación Bosque Protector',
                'subtitle' => 'Vigilancia y conservación del medio ambiente',
                'description' => 'Misión para proteger y preservar áreas boscosas amenazadas por actividades ilegales.',
                'date' => '2024-06-10',
                'status' => 'En espera de ejecución',
                'type' => 'Conservación',
                'priority' => 'Alta',
                'objective' => 'Evitar la tala ilegal y la caza furtiva en áreas forestales protegidas',
                'action' => 'Patrullaje y vigilancia constante en áreas boscosas designadas',
                'result' => 'En espera de ejecución',
                'photo' => 'barco.jpg',
                'army_id' => 2,
                'destination_id' => 9,
                'user_id' => 3,
            ],
            [
                'title' => 'Operación Seguridad Urbana',
                'subtitle' => 'Patrullaje en áreas urbanas',
                'description' => 'Misión de patrulla en zonas urbanas para prevenir el crimen y mantener el orden público.',
                'date' => '2024-06-15',
                'status' => 'En progreso',
                'type' => 'Seguridad Ciudadana',
                'priority' => 'Media',
                'objective' => 'Mantener la seguridad y tranquilidad en áreas urbanas',
                'action' => 'Patrullaje a pie y en vehículos por calles y plazas',
                'result' => 'En progreso',
                'photo' => 'barco.jpg',
                'army_id' => 2,
                'destination_id' => 10,
                'user_id' => 1,
            ],

            // Armada (ID: 3)
            [
                'title' => 'Operación Aguas Tranquilas',
                'subtitle' => 'Patrulla en alta mar',
                'description' => 'Misión de patrulla en aguas internacionales para prevenir la piratería y el contrabando.',
                'date' => '2024-06-02',
                'status' => 'En progreso',
                'type' => 'Patrulla Marítima',
                'priority' => 'Alta',
                'objective' => 'Mantener la seguridad en aguas internacionales',
                'action' => 'Patrullaje constante en alta mar y detección de actividades sospechosas',
                'result' => 'En progreso',
                'photo' => 'barco.jpg',
                'army_id' => 3,
                'destination_id' => 9,
                'user_id' => 2,
            ],
            [
                'title' => 'Operación Rescate en Altamar',
                'subtitle' => 'Asistencia en emergencias marítimas',
                'description' => 'Misión de rescate y asistencia a embarcaciones en peligro en aguas internacionales.',
                'date' => '2024-06-07',
                'status' => 'En progreso',
                'type' => 'Rescate',
                'priority' => 'Alta',
                'objective' => 'Brindar ayuda a embarcaciones en problemas en alta mar',
                'action' => 'Localización y asistencia a barcos en peligro',
                'result' => 'En progreso',
                'photo' => 'barco.jpg',
                'army_id' => 3,
                'destination_id' => 8,
                'user_id' => 3,
            ],
            [
                'title' => 'Operación Protección de la Pesca',
                'subtitle' => 'Vigilancia en áreas de pesca',
                'description' => 'Misión para proteger y controlar la actividad pesquera en aguas nacionales.',
                'date' => '2024-06-12',
                'status' => 'En espera de ejecución',
                'type' => 'Control Pesquero',
                'priority' => 'Media',
                'objective' => 'Evitar la pesca ilegal y proteger los recursos marinos',
                'action' => 'Patrullaje y control de embarcaciones pesqueras',
                'result' => 'En espera de ejecución',
                'photo' => 'barco.jpg',
                'army_id' => 3,
                'destination_id' => 7,
                'user_id' => 1,
            ],
            // Puedes agregar más misiones aquí según tus necesidades
        ];
        foreach ($missionData as $data) {
            Mission::create($data);
        }
    }
}
